DROP TABLE procedures IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE IF EXISTS global_seq;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(200)                     NOT NULL,
  email            VARCHAR(100)                     NOT NULL,
  password         VARCHAR(64)                      NOT NULL,
  registered       TIMESTAMP DEFAULT now()          NOT NULL,
  role             VARCHAR(20) DEFAULT 'ROLE_USER'  NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE procedures
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(200)                     NOT NULL,
  specialist       VARCHAR(255)                     NOT NULL,
  price            NUMERIC(6,2)                     NOT NULL,
  --   date
  date             VARCHAR(20)                      NOT NULL,
  room             INTEGER                          NOT NULL,
  CONSTRAINT procedures_unique_idx UNIQUE (specialist, date, room)
);